stages:
  preprocess:
    cmd: python src/preprocess.py
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: python src/train.py
    deps:
      - data/processed/train.csv
      - src/train.py
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/test.py
    deps:
      - models/model.pkl
      - data/processed/test.csv
    metrics:
      - experiments/results.json
