dataset: data/loan_data.csv

preprocessing:
  scale: True
  encode: True

model:
  type: RandomForestClassifier
  params:
    n_estimators: 150
    max_depth: 10
    random_state: 42

training:
  test_size: 0.2
  random_state: 42